version: "3.9"
   
services:
  app_django:
    build: .
    command: poetry run python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 8800:8000
    depends_on:
      - app_db
    networks:
      - djangonetwork
  app_db:
    image: postgres:14
    volumes:
      - data_db:/var/lib/postgresql/datac
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=dbtest
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=postgres
    networks:
    - djangonetwork
volumes:
  data_db:
networks:
  djangonetwork:
    driver: bridge