# Generated by Django 3.2 on 2022-07-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='email',
            field=models.EmailField(
                blank=True, max_length=254, verbose_name='email address',
            ),
        ),
    ]
