# Generated by Django 3.2 on 2022-05-18 02:27

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_product_img_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallery",
            name="img",
        ),
        migrations.AddField(
            model_name="gallery",
            name="img_product",
            field=models.FileField(
                blank=True,
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to="maps/",
            ),
        ),
    ]
