# Generated by Django 3.2 on 2022-05-24 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_cartitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='app.order',
            ),
        ),
    ]
