# Generated by Django 3.2 on 2022-05-18 02:27
from __future__ import annotations

import gdstorage.storage
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_img_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='img',
        ),
        migrations.AddField(
            model_name='gallery',
            name='img_product',
            field=models.FileField(
                blank=True,
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to='maps/',
            ),
        ),
    ]
