# Generated by Django 3.2 on 2022-05-19 00:47
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220518_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='prod_gallery',
                to='app.product',
            ),
        ),
    ]
