# Generated by Django 3.2 on 2022-07-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220707_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='status',
            field=models.CharField(
                choices=[('W', 'Waiting'), ('C', 'Created Order')], default='N', max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value_discount',
            field=models.FloatField(),
        ),
    ]
