# Generated by Django 3.2 on 2022-07-21 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220720_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='status',
            field=models.CharField(
                choices=[('C', 'Created Order'), ('W', 'Waiting')], default='N', max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(
                limit_choices_to={
                    'is_active': True,
                }, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
