# Generated by Django 3.2 on 2022-05-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_cartitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='code_verify',
            field=models.CharField(default='', max_length=255),
        ),
    ]
