# Generated by Django 3.2 on 2022-07-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_cartitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='status',
            field=models.CharField(
                choices=[('W', 'Waiting'), ('C', 'Created Order')], default='W', max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='cart_item',
            field=models.ManyToManyField(
                limit_choices_to={
                    'status': 'W',
                }, related_name='order_cartitem', to='app.CartItem',
            ),
        ),
    ]
