# Generated by Django 3.2 on 2022-05-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_customeruser_code_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='code_verify',
            field=models.CharField(max_length=255),
        ),
    ]
