# Generated by Django 3.2 on 2022-05-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_customeruser_code_verify'),
    ]

    operations = [
        migrations.CreateModel(
            name='blacklist',
            fields=[
                (
                    'id', models.BigAutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('access_token', models.CharField(max_length=255)),
            ],
        ),
    ]
