# Generated by Django 3.2 on 2022-06-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220531_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('N', 'New'), ('C', 'Confirmed'), (
                        'S', 'Shipped Out',
                    ), ('R', 'Received'),
                ], default='N', max_length=1,
            ),
        ),
    ]
