# Generated by Django 3.2 on 2022-06-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('N', 'New'), ('Co', 'Confirmed'), (
                        'S', 'Shipped Out',
                    ), ('R', 'Received'), ('Ca', 'Cancel'),
                ], default='N', max_length=2,
            ),
        ),
    ]
