# Generated by Django 3.2 on 2022-06-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20220614_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NE', 'New'), ('CO', 'Confirmed'), ('SH', 'Shipped Out'), ('RE', 'Received'), ('SU', 'Success'), ('CA', 'Cancel')], default='NE', max_length=2),
        ),
    ]
