# Generated by Django 3.2 on 2022-06-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='day_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='membership',
            name='voucher',
            field=models.FloatField(),
        ),
    ]
