# Generated by Django 3.2 on 2022-06-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20220614_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='value_discount',
            field=models.IntegerField(default=0),
        ),
    ]
