# Generated by Django 3.2 on 2022-06-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_discount_value_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='value_discount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
