# Generated by Django 3.2 on 2022-07-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='order',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='order',
            field=models.ManyToManyField(
                related_name='orderitem', to='app.Order',
            ),
        ),
    ]
