# Generated by Django 3.2 on 2022-07-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20220704_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_item',
            field=models.ManyToManyField(
                related_name='orderitem', to='app.CartItem',
            ),
        ),
    ]
