# Generated by Django 3.2 on 2022-07-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20220704_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(
                choices=[('C', 'Created order'), ('N', 'New')], default='N', max_length=1,
            ),
        ),
    ]
