# Generated by Django 3.2 on 2022-07-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_cartitem_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='customeruser',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='status',
            field=models.CharField(
                choices=[('W', 'Waiting'), ('C', 'Created Order')], default='N', max_length=1,
            ),
        ),
    ]
