# Generated by Django 3.2 on 2022-07-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20220704_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='status',
            field=models.CharField(
                choices=[('C', 'Created Order'), ('W', 'Waiting')], default='N', max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
