# Generated by Django 3.2 on 2022-07-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20220704_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_item',
            field=models.ManyToManyField(
                related_name='order_cartitem', to='app.CartItem',
            ),
        ),
    ]
